[package]
name = "quad-compress"
version = "0.1.0"
authors = ["skanaar <daniel.kallin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.4"